#!/bin/bash

a=$(./randall -o 5 -i COPYING 20 | wc -c); if [ $a -eq 20 ]; then echo 'success'; else echo 'fail'; fi

a=$(./randall -i rdrand -o stdio 30 | wc -c); if [ $a -eq 30 ]; then echo 'success'; else echo 'fail'; fi

a=$(./randall -o 5 10 | wc -c); if [ $a -eq 10 ]; then echo 'success'; else echo 'fail'; fi

a=$(./randall -i mrand48_r 10 | wc -c); if [ $a -eq 10 ]; then echo 'success'; else echo 'fail'; fi

a=$(./randall 5 | wc -c); if [ $a -eq 5 ]; then echo 'success'; else echo 'fail'; fi
